name: wallet_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-268.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  gap: ^3.0.1
  hive: null
  hive_flutter: null
  intl: ^0.19.0
  meta: ^1.12.0
  table_calendar: ^3.1.1

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
